### ISSUE TITLE
Issue with scanpy logging run_conga.py

### ISSUE THREAD

**Issue by sschattgen** [phbradley/conga#10]
Setting up the conda environment configuration from the README with Python 3.6 is now giving the following error when using the run_conga.py script. 

`Traceback (most recent call last):
  File "/Users/sschattg/opt/anaconda3/envs/conga_env_36/lib/python3.6/site-packages/sinfo/main.py", line 195, in sinfo
    mod_version = _find_version(mod.__version__)
AttributeError: module 'importlib_metadata' has no attribute '__version__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sschattg/conga/scripts/run_conga.py", line 155, in <module>
    sc.logging.print_versions() # goes to stdout
  File "/Users/sschattg/opt/anaconda3/envs/conga_env_36/lib/python3.6/site-packages/scanpy/logging.py", line 161, in print_versions
    sinfo(dependencies=True)
  File "/Users/sschattg/opt/anaconda3/envs/conga_env_36/lib/python3.6/site-packages/sinfo/main.py", line 198, in sinfo
    mod_version = _find_version(mod.version)
  File "/Users/sschattg/opt/anaconda3/envs/conga_env_36/lib/python3.6/site-packages/sinfo/main.py", line 42, in _find_version
    return mod_version_attr()
TypeError: version() missing 1 required positional argument: 'distribution_name'`

**Comment by sschattgen** [comment]
run_conga.py eidted to skip sc.logging.print_versions() for now.
