### ISSUE TITLE
Question about using previously integrated gex data

### ISSUE THREAD

**Issue by s2hui** [phbradley/conga#28]
Hello,

In the example on merging multiple data sets, the individual sample clones and companion gex are supplied in a txt file and inputted into the merge_samples.py script.

What I have are the individual clone files and one integrated gex file.  What would be appropriate way to go about analyzing my data?

Would it make sense to supply the converted integrated gex data (i.e. mtx or h5 format) as the companion file for each clone in the sample.txt file?

Appreciate your insight,
@s2hui

**Comment by sschattgen** [comment]
Hi,

Assuming the barcode suffixes match between the clones files and the gex matrix, you could run each sample individually since any cells without tcr information would be excluded. But if you’d like to run it all together then 
I’d recommend using the `make_10x_clones_file_batch` function (which we need to document better). You can use a metadata csv file with two columns, “file” containing the paths to each of the filtered_contig_annotations.csv files, and “suffix” which should contain the 
 barcode suffix for matching that sample to the corresponding cells in your aggregate gex matrix. This will merge each of the files into a single output clones file that can then be passed to `run_conga.py` with your gex file.

**Comment by s2hui** [comment]
Hi,

Thanks for detailed instructions!  

I renamed the barcodes in my integrated Seurat object to be of the format: prefix-barcode (stripped off the -1 at the end and replaced the _ with a - in between the prefix and barcode).  Then I converted the object into mtx using the `write10xCounts` method within R.

Then I made a batch.csv file with two columns (format below):

file,batch_id
filtered_contig_annotations.csv,prefix

Then I ran `make_10x_clones_file_batch`  but get the following error:

```
Python 3.7.2 (default, Dec 29 2018, 06:19:36) [GCC 7.3.0]
Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-centos-7.9.2009-Core
62 logical CPU cores, x86_64
-----
Session information updated at 2021-10-18 17:37

reading: /cluster/projects/finelligroup/scKidneyCancer/out_shirley/conga/out/mtx of type 10x_mtx
total barcodes: 113730 (113730, 34271)
reading: /cluster/projects/finelligroup/scKidneyCancer/out_shirley/conga/out/merged_remedy/merged_remedy_clones.tsv
reading: /cluster/projects/finelligroup/scKidneyCancer/out_shirley/conga/out/merged_remedy/merged_remedy_clones_AB.dist_50_kpcs
Reducing to the 0 barcodes (out of 113730) with paired TCR sequence data
Traceback (most recent call last):
  File "/cluster/home/hshirley/conga/scripts/run_conga.py", line 378, in <module>
    suffix_for_non_gene_features = args.suffix_for_non_gene_features,
  File "/cluster/home/hshirley/conga/conga/preprocess.py", line 393, in read_dataset
    store_tcrs_in_adata( adata, tcrs )
  File "/cluster/home/hshirley/conga/conga/preprocess.py", line 168, in store_tcrs_in_adata
    adata.obs['cdr3a_nucseq'] = adata.obs.cdr3a_nucseq.str.lower()
  File "/cluster/home/hshirley/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5456, in __getattr__
    return object.__getattribute__(self, name)
  File "/cluster/home/hshirley/.local/lib/python3.7/site-packages/pandas/core/accessor.py", line 180, in __get__
    accessor_obj = self._accessor(obj)
  File "/cluster/home/hshirley/.local/lib/python3.7/site-packages/pandas/core/strings/accessor.py", line 154, in __init__
    self._inferred_dtype = self._validate(data)
  File "/cluster/home/hshirley/.local/lib/python3.7/site-packages/pandas/core/strings/accessor.py", line 218, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!

```

I'm not sure if it is the cause but when I look inside the resulting aggregated clones mappings file, I see that all the prefix-barcodes have -1-0 appended, so it looks like:

prefix-barcode-1-0

This format doesn't match any barcodes in the gex data file as the barcodes were renamed to be prefix_barcode.

I wonder what the issue is?  Thanks for your help!
@s2hui

**Comment by leeanapeters** [comment]
Hi I am having an issue with combining keeping the batch parameters to compare groups and performing the make_10x_clones_file_batch merge. 

I performed the procedure as above but then modified my adata object using a batch_info file (containing barcodes and other metadata ie patient and condition) and set those as the batch keys.

When I attempt to use the clone file generated from the make_10x_clones_file_batch along with the gex exported from the adata object, I receive this error even though the mapping file is in the same directory
 assert exists(kpca_file)
AssertionError. 

When I use --no_kpca i receive this error: 
total barcodes: 18863 (18863, 18327)
reading: all_clones_w_prefix_added.tsv
WARNING: missing kpca_file: all_clones_w_prefix_added_AB.dist_50_kpcs
WARNING: X_tcr_pca will be empty
Reducing to the 0 barcodes (out of 18863) with paired TCR sequence data

Any help would be appreciated!


Leeana

**Comment by phbradley** [comment]
Hi there,
For some reason I am having trouble seeing the context for this email on github. Is this a post on one of the open issues, or is it an email directly to me? So, when you say below, "I performed the procedure as above" I can't figure out what that refers to.
Maybe include a bit more context or let me know which issue it is? When I click on issue #28 (from the subject line) I don't see the post.
Take care,
Phil

________________________________
