### ISSUE TITLE
failed in merge_samples.py

### ISSUE THREAD

**Issue by JingwenD** [phbradley/conga#33]
Hi,

I am failing to get merge object using merge_samples.py.

I get an error:
```
Traceback (most recent call last):
  File "~/CoNGA/conga/scripts/merge_samples.py", line 83, in <module>
    assert exists(bcmap_file)
AssertionError
```
My code is:
```
python3 ~/CoNGA/conga/scripts/merge_samples.py \
--samples sampla_list.txt \
--output_clones_file merged_pbmc_clones.tsv \
--output_gex_data merged_pbmc_gex.h5ad \
--organism human 

```
Thanks for the development of CoNGA ！
Looking forward to your reply.

Best，

Jingwen

**Comment by phbradley** [comment]
Hi Jingwen,
Thanks for trying conga! It looks like the script is having trouble finding the barcode mapping file, which connects the clone_id's in the clones file to the barcodes in the GEX data. Each line of the samples file should correspond to a dataset that can be run on its own through conga. So it should have a clones file, a GEX file, and assuming the clones file was made by the setup_10x_for_conga.py script, there should be a file with a name like <clones_file>.barcode_mapping.tsv. That's the file it seems to be having trouble finding. Can you double-check that for each clones file in the samples file, there is such a barcode mapping file?

**Comment by JingwenD** [comment]
Hi Philip,

Thanks for you reply. Indeed, we made some mistake when making the sample list table. We finished the merging after fixing this issue.

But we got into the other issue when running the run_conga.py:

```
Python 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-centos-7.9.2009-Core
24 logical CPU cores, x86_64
-----
Session information updated at 2021-11-28 14:15

reading: /hpc/dla_lti/jdeng/scRNASeq/PBMC/merged_pbmc_gex.h5ad of type h5ad
/hpc/dla_lti/jdeng/sandbox/gitrepos/conga/conga/preprocess.py:221: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if adata.isview: # ran into trouble with AnnData views vs copies
total barcodes: 91926 (91926, 36601)
Traceback (most recent call last):
  File "gitrepos/conga/scripts/run_conga.py", line 300, in <module>
    suffix_for_non_gene_features = args.suffix_for_non_gene_features,
  File "/hpc/dla_lti/jdeng/sandbox/gitrepos/conga/conga/preprocess.py", line 299, in read_dataset
    assert exists(kpca_file)
AssertionError
```

It seems fail to load the kpca information. 

Shoud I need to remove the `--no_kpca` flag when running setup_10x_for_conga.py?

**Comment by phbradley** [comment]
Hi Jingwen,
Glad the merging worked! You could either add `--no_kpca` when running run_conga.py or remove the `--no_kpca` flag from merge_samples.py (ie, make sure that the kpca is run during the merging step). If the merged set is big (>10K clonotypes), the kpca on the merged dataset can take a long time/use lots of memory. So running run_conga.py with `--no_kpca` is the way to go for really big datasets. 

Let me know if that's not clear.
Take care,
Phil

**Comment by JingwenD** [comment]
Hi Philip,

It is nice of you for the prompt reply.
We solved the problem by adding the `--no_kpca` when running run_conga.py.
But it is pity that it ends with the error that is about the library issue in our HPC environment.
```
running 1D UMAP gex
ran louvain clustering: louvain_gex
preprocess.cluster_and_tsne_and_umap:: X_pca_tcr is not present in adata.obsm; using exact tcrdist nbrs for umap and clustering
util.run_command: cmd= /hpc/dla_lti/jdeng/sandbox/gitrepos/conga/tcrdist_cpp/bin/find_neighbors -f tmp_tcrdists551_tcrs.tsv -n 10 -d /hpc/dla_lti/jdeng/sandbox/gitrepos/conga/tcrdist_cpp/db/tcrdist_info_human.txt -o tmp_tcrdists551_calc_tcrdist
/hpc/dla_lti/jdeng/sandbox/gitrepos/conga/tcrdist_cpp/bin/find_neighbors: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /hpc/dla_lti/jdeng/sandbox/gitrepos/conga/tcrdist_cpp/bin/find_neighbors)
/hpc/dla_lti/jdeng/sandbox/gitrepos/conga/tcrdist_cpp/bin/find_neighbors: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /hpc/dla_lti/jdeng/sandbox/gitrepos/conga/tcrdist_cpp/bin/find_neighbors)
/hpc/dla_lti/jdeng/sandbox/gitrepos/conga/tcrdist_cpp/bin/find_neighbors: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /hpc/dla_lti/jdeng/sandbox/gitrepos/conga/tcrdist_cpp/bin/find_neighbors)
find_neighbors failed: False False
```

I tried to re-run it in local computer. But the computer could not handle such big dataset.

Sorry to disturb you in weekend.

Bset,

Jingwen

**Comment by phbradley** [comment]
Hi Jingwen,
I'm sorry! That's really too bad. I wonder whether compiling the C++ code within the cluster environment might help with that... Good luck!
Take care,
Phil

**Comment by JingwenD** [comment]
Hi Philip,

Finally, I got the kpca file `merged_pbmc_clones_AB.dist_50_kpcs` , so that I can skip the tcrdist calculation step in `run_conga.py`. I assigned the `--kpca_file` in my command:

```
python3 gitrepos/conga/scripts/run_conga.py \
--gex_data /hpc/dla_lti/jdeng/scRNASeq/PBMC/conga_gex \
--gex_data_type 10x_mtx \
--clones_file /hpc/dla_lti/jdeng/scRNASeq/PBMC/merged_pbmc_clones.tsv \
--organism human \
--graph_vs_graph \
--outfile_prefix /hpc/dla_lti/jdeng/scRNASeq/PBMC/merged_pbmc_outs/merged_pbmc \
--kpca_file /hpc/dla_lti/jdeng/scRNASeq/PBMC/merged_pbmc_clones_AB.dist_50_kpcs
```

But it seems fail to read all these files into the AnnData:

```
reading: /hpc/dla_lti/jdeng/scRNASeq/PBMC/conga_gex of type 10x_mtx
/hpc/dla_lti/jdeng/sandbox/gitrepos/conga/conga/preprocess.py:221: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  if adata.isview: # ran into trouble with AnnData views vs copies
total barcodes: 39657 (39657, 19658)
reading: /hpc/dla_lti/jdeng/scRNASeq/PBMC/merged_pbmc_clones.tsv
reading: /hpc/dla_lti/jdeng/scRNASeq/PBMC/merged_pbmc_clones_AB.dist_50_kpcs
Traceback (most recent call last):
  File "gitrepos/conga/scripts/run_conga.py", line 300, in <module>
    suffix_for_non_gene_features = args.suffix_for_non_gene_features,
  File "/hpc/dla_lti/jdeng/sandbox/gitrepos/conga/conga/preprocess.py", line 374, in read_dataset
    kpcs = tcr2kpcs[tcr]
KeyError: (('TRAV8-3*01', 'TRAJ9*01', 'CAVGGTGGFKTIF', 'tgtgctgtgggggggactggaggcttcaaaactatcttt'), ('TRBV28*01', 'TRBJ2-5*01', 'CASSPTGRDEETQYF', 'tgtgccagcagcccaaccggcagggatgaagagacccagtacttc'))
```

Did I assigned the wrong files?

As my `merged_pbmc_clones_AB.dist_50_kpcs` likes this:
```
pc_comps: clonotype837-18 0.054670 -0.197568 0.046564 0.078736 -0.065816 0.037781 -0.125707 0.096287 -0.092125 -0.072257 0.043961 -0.089393 0.103154 -0.058483 0.182067 0.027975 0.045229 0.016712 -0.004055 0.067821 0.012372 0.054367 -0.099393 0.048736 -0.056652 -0.003006 -0.038619 -0.098005 -0.098646 -0.084614 0.081781 -0.098372 -0.060183 0.047666 -0.034190 -0.016948 -0.000928 -0.113831 -0.076584 0.127649 0.070713 -0.041117 -0.041969 -0.040549 0.032892 0.150841 -0.045149 0.016300 -0.010089 -0.080844
pc_comps: clonotype91-18 0.322059 0.227119 0.068020 0.201332 0.108896 0.038991 -0.002607 0.013110 0.096899 0.126934 0.040040 0.057937 -0.043024 -0.038260 -0.100646 0.018594 -0.065578 -0.011115 0.010631 -0.041703 -0.007042 -0.037258 -0.024081 0.040278 0.039893 -0.067307 -0.063539 0.014541 -0.076263 -0.052919 0.045500 -0.083475 -0.060762 -0.022605 -0.006122 -0.024463 0.008252 0.007389 -0.011372 -0.005567 -0.015740 -0.059809 0.102468 -0.029286 0.026579 0.018104 0.001399 0.063998 0.217604 -0.024245
```

And my `merged_pbmc_clones.tsv` likes this:
```
clonotype837-18	UNK_S	1	TRAV21*01	TRAJ39*01			TRBV13*01	TRBJ2-7*01	CAVRGAGNMLTF	tgtgctgtgaggggtgcaggcaacatgctcaccttt			CASSLTRGLAGDPYEQYFtgtgccagcagcttaactaggggactagcgggggacccctacgagcagtacttc	1	0	1	1	1
clonotype91-18	UNK_S	1	TRAV16*01	TRAJ9*01			TRBV20-1*01	TRBJ1-4*01	CAPGGFKTIF	tgtgctccgggaggcttcaaaactatcttt			CSARGDRGEKLFF	tgcagtgctaggggggacaggggcgaaaaactgtttttt	1	0	1	1	1
clonotype92-18	UNK_S	1	TRAV1-2*01	TRAJ33*01			TRBV29-1*01	TRBJ2-7*01	CAAMDSNYQLIW	tgtgctgccatggatagcaactatcagttaatctgg			CSVADRDPYEQYF	tgcagcgttgctgacagggacccctacgagcagtacttc	1	0	1	1	1
clonotype93-18	UNK_S	1	TRAV26-2*01	TRAJ20*01	TRAV35*01	TRAJ48*01	TRBV20-1*01	TRBJ1-4*01	CILSPGSTDYKLSF	tgcatcctgagtcccgggtccaccgactacaagctcagcttt	CAGLLISNFGNEKLTF	tgtgctggccttcttatatctaactttggaaatgagaaattaaccttt	CSASGGTNEKLFF	tgcagtgctagcgggggaactaatgaaaaactgtttttt	2	1	2	2	1
```

The tcrdist combines with gex is really cool. I hope I can figure out how to make it done on my data set.

Best,

Jingwen

**Comment by JingwenD** [comment]
Hi Philip,

We made it done in another HPC environment, for TCR, and BCR as well. Again, thanks for the development of CoNGA. It is pretty cool!

Best,
Jingwen

**Comment by phbradley** [comment]
OK, great! Glad it worked!
Take care,
PHil

________________________________
